## Updating Data Exercise

**This exercise uses the `netflix_titles.csv` dataset**

In [4]:
# read in the netflix_titles.csv dataset.  Make sure to tell pandas to use the correct separator character!
import pandas as pd
df = pd.read_csv("netflix_titles.csv", sep="|", index_col=0)
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [5]:
# set the index to be the "show_id" (inplace)
df.set_index("show_id", inplace=True)
df

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [6]:
# Find the row with the id of s2202 and set its director to "Greg Whiteley"
df.loc[["s2202"], ["director"]] = "Greg Whiteley"
df.loc[["s2202"]]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s2202,TV Show,Last Chance U,Greg Whiteley,"John Franklin III, DJ Law, Buddy Stephens, Bri...",United States,"July 28, 2020",2020,TV-MA,5 Seasons,Docuseries,In a docuseries set at one of NCAA football's ...

In [7]:
#Update the "duration" of the shows with index s2881 and s3601 to be "GONE TOO SOON"
df.loc[["s2881", "s3601"], ["duration"]] = "GONE TOO SOON"
df.loc[["s2881", "s3601"]]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s2881,TV Show,I Am Not Okay With This,NaN,"Sophia Lillis, Wyatt Oleff, Kathleen Rose Perk...",United States,"February 26, 2020",2020,TV-MA,GONE TOO SOON,"TV Comedies, TV Dramas, TV Sci-Fi & Fantasy","Angsty Syd navigates high school awkwardness, ..."
s3601,TV Show,GLOW,NaN,"Alison Brie, Betty Gilpin, Marc Maron, Britney...",United States,"August 9, 2019",2019,TV-MA,GONE TOO SOON,"TV Comedies, TV Dramas","In 1980s LA, a crew of misfits reinvent themse..."

In [11]:
#rename the release_year column to "release_yr" in place
df.rename(mapper={"release_year": "release_yr"}, axis=1, inplace=True)
# OR 
df.rename(columns={"release_year": "release_yr"}, inplace=True)
df

,type,title,director,cast,country,date_added,release_yr,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [39]:
# Find the show called "Evil"
# Change its index label to s6666 inplace
df.loc[df["title"] == "Evil"]
df.rename(mapper={"s1907": "s6666"}, axis=0, inplace=True)
df.loc[df["title"] == "Evil"]

# df.drop(labels=["show_id"], axis=1, inplace=True)

,type,title,director,cast,country,date_added,release_yr,rating,duration,listed_in,description,is_fav
show_id,,,,,,,,,,,,
s6666,TV Show,Evil,NaN,"Katja Herbers, Mike Colter, Aasif Mandvi, Mich...",United States,"October 1, 2020",2019,TV-14,1 Season,TV Dramas,A forensic psychologist partners with a Cathol...,False

In [41]:
# In the rating column, please replace all instances of "UR" and "NR" with "No Rating".  Don't do it inplace!
df.loc[(df["rating"] == "UR") | (df["rating"] == "NR"), "rating"] = "No Rating"
# OR
df["rating"].replace(["UR", "NR"], "No Rating")

# To check,
df["rating"].replace(["UR", "NR"], "No Rating").value_counts()

TV-MA        3207
TV-14        2160
TV-PG         863
R             799
PG-13         490
TV-Y7         334
TV-Y          307
PG            287
TV-G          220
No Rating      83
G              41
TV-Y7-FV        6
NC-17           3
74 min          1
84 min          1
66 min          1
Name: rating, dtype: int64

In [37]:
# Add a new column "is_fav" and set it to False for all rows
# Update the "is_fav" column to True for the titles in my list of favs (provided below)
favs = ["Young Royals", "Dark", "Big Mouth", "BoJack Horseman", "The Queen's Gambit", "American Vandal", "Russian Doll", "Godless"]
df.insert(len(df.columns), "is_fav", False)
df.loc[df["title"].isin(favs), ["is_fav"]] = True
df.loc[df["title"].isin(favs)]

,type,title,director,cast,country,date_added,release_yr,rating,duration,listed_in,description,is_fav
show_id,,,,,,,,,,,,
s618,TV Show,Young Royals,NaN,"Edvin Ryding, Omar Rudberg, Malte Gårdinger, F...",Sweden,"July 1, 2021",2021,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Prince Wilhelm adjusts to life at his prestigi...,True
s1591,TV Show,Big Mouth,NaN,"Nick Kroll, John Mulaney, Jessi Klein, Jason M...",United States,"December 4, 2020",2020,TV-MA,4 Seasons,TV Comedies,Teenage friends find their lives upended by th...,True
s1805,TV Show,The Queen's Gambit,NaN,"Anya Taylor-Joy, Bill Camp, Marielle Heller, T...",United States,"October 23, 2020",2020,TV-MA,1 Season,TV Dramas,"In a 1950s orphanage, a young girl reveals an ...",True
s2328,TV Show,Dark,NaN,"Louis Hofmann, Oliver Masucci, Jördis Triebel,...","Germany, United States","June 27, 2020",2020,TV-MA,3 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",A missing child sets four families on a franti...,True
s3370,TV Show,BoJack Horseman,NaN,"Will Arnett, Aaron Paul, Amy Sedaris, Alison B...",United States,"October 25, 2019",2020,TV-MA,6 Seasons,TV Comedies,Meet the most beloved sitcom horse of the '90s...,True
s4143,TV Show,Russian Doll,NaN,"Natasha Lyonne, Charlie Barnett, Yul Vazquez, ...",United States,"February 1, 2019",2019,TV-MA,1 Season,"TV Comedies, TV Dramas",Nadia keeps dying and reliving her 36th birthd...,True
s4637,TV Show,American Vandal,NaN,"Tyler Alvarez, Griffin Gluck, Jimmy Tatro, Cam...",United States,"September 14, 2018",2018,TV-MA,2 Seasons,"Crime TV Shows, TV Comedies, Teen TV Shows",A high school is rocked by an act of vandalism...,True
s5160,TV Show,Godless,NaN,"Jeff Daniels, Michelle Dockery, Jack O'Connell...",United States,"November 22, 2017",2017,TV-MA,1 Season,TV Dramas,A ruthless outlaw terrorizes the West in searc...,True